language: ruby

rvm: 2.1.3

branches:
  only:
  - master

before_script:
  - 'bundle exec rake db:create db:migrate db:test:prepare'

addons:
  code_climate:
    repo_token: <%= ENV['CODECLIMATE_REPO_TOKEN'] %>